language: go

go:
  - 1.7.x
install:
  - go get github.com/gorilla/mux
  - go get github.com/go-sql-driver/mysql
  - go get -u github.com/jinzhu/gorm
  - go get github.com/erikstmartin/go-testdb
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - export GOPATH=$GOPATH:$TRAVIS_BUILD_DIR
  - ln -s $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR../src
  - go test -covermode=count -coverprofile=coverage.out ./api/v1/invoice/
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
