version: '2'
services:
    apiGoChallenge:
        image: golang:1.7.4
        container_name: apiGoChallenge
        command: bash -c '/go/src/build/go-challange'
        restart: always
        ports:
         - "8888:80"
        volumes:
         - ./:/go/src
        tty: true
        environment:
            DB_NAME: api
            DB_USER: api
            DB_PASS: api
            DB_HOST: apiMySqlChallenge:3306
            GOPATH: /go:/go/src

    apiMySqlChallenge:
        image: mysql:5.6
        container_name: apiMySqlChallenge
        restart: always
        volumes:
         - apiMySqlData:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: api
            MYSQL_DATABASE: api
            MYSQL_USER: api
            MYSQL_PASSWORD: api

volumes:
    apiMySqlData: {}
